name: Auto Pull Request and Merge
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - '*' # Trigger for all branches

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $BRANCH_NAME"
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated Pull Request'
          title: 'Automated Pull Request'
          branch: ${{ steps.branch_name.outputs.branch }}
          body: |
            Automated pull request created by a GitHub Action.

      - name: Merge Pull Request
        if: steps.create_pr.outputs.pull_request_created == 'true'
        run: |
          gh pr merge -A $PR_URL
