name: Auto Pull Request and Merge
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - '*' # Trigger for all branches

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated Pull Request'
          title: 'Automated Pull Request'
          branch: ${{ steps.branch_name.outputs.branch }}
          base: 'main'
          body: |
            Automated pull request created by a GitHub Action.

      - name: Merge Pull Request
        if: steps.create_pr.outputs.pull_request_created == 'true'
        run: |
          gh pr merge -B ${{ steps.branch_name.outputs.branch }} $PR_URL


